# Generated by Django 5.0.4 on 2024-04-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Shirt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="shirts")),
                ("description", models.TextField()),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("white", "White"),
                            ("black", "Black"),
                            ("red", "Red"),
                            ("green", "Green"),
                            ("blue", "Blue"),
                            ("yellow", "Yellow"),
                            ("orange", "Orange"),
                            ("purple", "Purple"),
                            ("pink", "Pink"),
                            ("gray", "Gray"),
                        ],
                        default="white",
                        max_length=100,
                    ),
                ),
                ("type", models.CharField(default="shirt", max_length=100)),
                ("tag", models.ManyToManyField(blank=True, to="core.tag")),
            ],
        ),
        migrations.CreateModel(
            name="Tshirt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="shirts")),
                ("description", models.TextField()),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("white", "White"),
                            ("black", "Black"),
                            ("red", "Red"),
                            ("green", "Green"),
                            ("blue", "Blue"),
                            ("yellow", "Yellow"),
                            ("orange", "Orange"),
                            ("purple", "Purple"),
                            ("pink", "Pink"),
                            ("gray", "Gray"),
                        ],
                        default="white",
                        max_length=100,
                    ),
                ),
                ("type", models.CharField(default="tshirt", max_length=100)),
                ("tag", models.ManyToManyField(blank=True, to="core.tag")),
            ],
        ),
    ]
